Add Author and Game Classes
MarwanDev/Ruby-Capstone pull request #35
Opened 2023-07-04 15:55 UTC by MarwanDev

## Add Author and Game Classes

### In this milestone I did the following:

- Create a Game class in a separate .rb file.
- Create an Author class with an association to the Item class (in a separate .rb file).
- All Game class properties visible in the diagram should be defined and set up in the constructor method.
- All Author class properties visible in the diagram should be defined and set up in the constructor method.
- Implement methods:
    - add_item method in the Author class
        - should take an instance of the Item class as an input
        - should add the input item to the collection of items
        - should add self as a property of the item object (by using the correct setter from the item object)
    - can_be_archived?() in the Game class
        - should override the method from the parent class
        - should return true if parent's method returns true AND if last_played_at is older than 2 years
        - otherwise, it should return false

2023-07-04 15:57 UTC, MarwanDev commented
Hi, @ehmaddd Could @stephenkati  one of you review my PR?

2023-07-04 16:13 UTC, ehmaddd commented on classes/author.rb
> +  attr_accessor :name, :items
First name and Last names should be separately stored in two individual variables

2023-07-04 16:14 UTC, ehmaddd commented on classes/author.rb
> +    @name = name
First name and Last names should be separately stored in two individual variables

2023-07-04 19:25 UTC, MarwanDev commented
@ehmaddd Changes have been applied. Feel free to review whenever you have time

2023-07-05 04:42 UTC, stephenkati requested changes
# STATUS: CHANGES REQUESTED :recycle: 
Hi @MarwanDev,

Good job so far. Just a few changes remaining.

## Highlights

- No Linter errors 👍 
- Clean Code 😄

2023-07-05 04:42 UTC, stephenkati commented on spec/game_spec.rb
> +    @game.publish_date.should eql '2018/06/15'
use of `should` is **deprecated**.
I suggest you use `expect` instead

For example:
sh
```
expect(@game).to be_an_instance_of(Game)
expect(@game.multiplayer).to be true
expect(@game.last_played).to be eq('your date')
expect(@game.publish_date).to be eq('your date)
```

2023-07-05 07:49 UTC, stephenkati approved these changes
# STATUS: APPROVED 🟢 
Hi @MarwanDev , Congratulations, Pull Request is approved and ready to be merged
#
## Highlights

- No Linter errors:heavy_check_mark:  
- Clean Code  :heavy_check_mark:

2023-07-05 07:49 UTC, merged